[workspace]
resolver = "2"
members = [
  "lana/*",
  "core/*",
  "lib/*",
  "dev/entity-rollups",
  "dev/check-dependency-dag",
  "workspace-hack",
]
exclude = [
  "lib/js",
]

[workspace.package]
version = "0.0.0"

[workspace.dependencies]
# Internal dependencies
# Lib dependencies
airflow = { path = "lib/airflow" }
audit = { path = "lib/audit" }
authz = { path = "lib/authz" }
bitgo = { path = "lib/bitgo" }
cloud-storage = { path = "lib/cloud-storage" }
jwks-utils = { path = "lib/jwks-utils" }
keycloak-client = { path = "lib/keycloak-client" }
komainu = { path = "lib/komainu" }
outbox = { path = "lib/outbox" }
rendering = { path = "lib/rendering" }
smtp-client = { path = "lib/smtp-client" }
sumsub = { path = "lib/sumsub" }
tracing-utils = { path = "lib/tracing-utils" }

# Core dependencies
core-access = { path = "core/access" }
core-accounting = { path = "core/accounting" }
core-applicant = { path = "core/applicant" }
core-credit = { path = "core/credit" }
core-custody = { path = "core/custody" }
core-customer = { path = "core/customer" }
core-deposit = { path = "core/deposit" }
core-money = { path = "core/money" }
core-price = { path = "core/price" }
core-report = { path = "core/report" }
document-storage = { path = "core/document-storage" }
governance = { path = "core/governance" }
public-id = { path = "core/public-id" }

# Lana dependencies
admin-server = { path = "lana/admin-server" }
contract-creation = { path = "lana/contract-creation" }
customer-server = { path = "lana/customer-server" }
customer-sync = { path = "lana/customer-sync" }
dashboard = { path = "lana/dashboard" }
deposit-sync = { path = "lana/deposit-sync" }
lana-app = { path = "lana/app" }
lana-events = { path = "lana/events" }
lana-ids = { path = "lana/ids" }
notification = { path = "lana/notification" }
rbac-types = { path = "lana/rbac-types" }
sim-bootstrap = { path = "lana/sim-bootstrap" }
user-onboarding = { path = "lana/user-onboarding" }

# External dependencies
es-entity = { version = "0.10.5", features = ["event-context", "tracing-context", "instrument"] }
cala-ledger = "0.12.12"
job = "0.2.11"
sim-time = "0.10"
cala-cel-interpreter = "0.12"

aes = "0.8"
anyhow = "1.0.100"
async-graphql = { version = "7.0.17", default-features = false, features = [
  "dataloader",
  "chrono",
  "playground",
  "tempfile",
  "tracing",
] }
async-graphql-axum = "7.0.17"
async-trait = "0.1.89"
axum = { version = "0.8.7", features = ["macros"] }
axum-extra = { version = "0.12.2", default-features = false, features = [
  "tracing",
  "typed-header",
] }
bip32 = "0.5"
ccm = "0.5"
csv = "1.4.0"
chrono = { version = "0.4.42", features = [
  "clock",
  "serde",
], default-features = false }
clap = { version = "4.5.53", features = ["derive", "env"] }
derive_builder = "0.20.0"
graphql_client = { version = "0.14.0", features = ["reqwest-rustls"] }
sqlx = { version = "0.8", features = [
  "runtime-tokio-rustls",
  "postgres",
  "rust_decimal",
  "uuid",
  "chrono",
  "json",
] }
thiserror = "2.0.17"
uuid = { version = "1.18", features = ["serde", "v4"] }
log = "0.4"
tracing = "0.1.41"
tracing-opentelemetry = "0.32.0"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
opentelemetry = { version = "0.31.0" }
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.31.0", default-features = false, features = [
  "http-proto",
  "grpc-tonic",
  "reqwest-client",
  "reqwest-rustls-webpki-roots"
] }
opentelemetry-http = "0.31.0"
opentelemetry-semantic-conventions = { version = "0.31.0", features = ["semconv_experimental"] }
tokio = { version = "1.48.0", features = [
  "rt-multi-thread",
  "macros",
  "time",
  "sync",
  "signal",
] }
tokio-stream = { version = "0.1.16", features = ["sync"] }
strum = { version = "0.27", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.32"
serde_json = "1.0.145"
serde_with = "3.16.1"
futures = "0.3.29"
http = "1.4"
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls", "charset", "http2", "macos-system-configuration", "multipart"] }
url = { version = "2.5", features = ["serde"] }
rust_decimal_macros = "1.39.0"
rust_decimal = "1.38.0"
rusty-money = { version = "0.4", features = ["iso", "crypto"] }
base64 = { version = "0.22.1" }
jsonwebtoken = { version = "10.2.0", default-features = false, features = ["aws_lc_rs"] }
hex = "0.4.3"
hmac = "0.12.1"
sha2 = "0.10.8"
tower-http = { version = "0.6.7", features = ["cors"] }
lettre = { version = "0.11.19", default-features = false, features = ["builder", "tokio1", "tokio1-rustls-tls", "smtp-transport"] }
sqlx-adapter = { version = "1.8", default-features = false, features = [
  "postgres",
  "runtime-tokio-rustls",
] }
cached = { version = "0.56.0", features = ["async"] }
gcp_auth = { version = "0.12.2", default-features = false, features = ["webpki-roots"] }
google-cloud-storage = { version = "0.24.0", default-features = false, features = [
  "rustls-tls",
  "auth",
] }
rand = "0.9"
serial_test = { version = "3.2.0", features = ["file_locks"] }
chacha20poly1305 = "0.10.1"
handlebars = "6.3.2"
schemars = { version = "1.1.0", features = ["derive", "chrono04", "rust_decimal1"] }
tempfile = "3.23.0"
p256 = "0.13.2"
pbkdf2 = "0.12"
pkcs8 = { version = "0.10.2", features = ["encryption"] }
markdown2pdf = { version = "0.1.9", features = ["rustls-tls"], default-features = false }
bytes = "1.11"
keycloak = "26.4.0"

[profile.release]
lto = true 

[workspace.metadata.crane]
name = "lana-bank"

[workspace.metadata.cargo-machete]
ignored = ["workspace-hack"]
