name: Hakari Generate on Cargo Dependabot PR

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "workspace-hack/**"

jobs:
  hakari-generate:
    if: >
      github.actor == 'dependabot[bot]' &&
      (startsWith(github.head_ref, 'dependabot/cargo/'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Skip if Hakari commit already exists
        run: |
            base_ref="${{ github.base_ref }}"
            git fetch origin "$base_ref"
            if git log --oneline --grep='^chore(hakari): re-generate workspace-hack$' "origin/${base_ref}..HEAD" | grep -q .; then
              echo "Hakari commit already exists on this PR branch. Exiting."
              exit 78
            fi
      - name: Install cargo-hakari
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hakari
      - name: Re-Generate workspace-hack
        run: cargo hakari generate
      - name: Commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[hakari-bot]"
            git config user.email "github-actions[hakari-bot]@noreply.galoy.io"
            git add .
            git commit -m "chore(hakari): re-generate workspace-hack"
            git push origin HEAD:"${{ github.event.pull_request.head.ref }}"
          fi

